# Generated by Django 2.1.2 on 2018-10-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181028_0305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postt',
        ),
    ]
