# Generated by Django 2.1.2 on 2018-10-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postt',
            new_name='Post',
        ),
    ]
